sylius_grid:
    grids:
        guiziweb_admin_platform_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: Guiziweb\SyliusAIPlatformBundle\Entity\PlatformConfiguration
            fields:
                code:
                    type: string
                    label: guiziweb_sylius_ai_platform.ui.code
                name:
                    type: string
                    label: guiziweb_sylius_ai_platform.ui.name
                provider:
                    type: string
                    label: guiziweb_sylius_ai_platform.ui.provider
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusAdmin/shared/grid/field/boolean.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete